spring:
  application:
    name: AudioBook
  # MySQL database connection settings
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/audio_book?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:quyetbh}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Hibernate settings (optional)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true


api:
  prefix: /api/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"