spring:
  application:
    name: AudioBook
  # MySQL database connection settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  # Hibernate settings (optional)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  config:
    import: env.properties

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds