spring:
  application:
    name: AudioBook
  # MySQL database connection settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  # Hibernate settings (optional)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  # Multipart file upload settings
  servlet:
    multipart:
      max-file-size: 10MB       # Giới hạn kích thước tối đa của một file
      max-request-size: 10MB    # Giới hạn kích thước tối đa của request
  # Static resources settings
  web:
    resources:
      static-locations:         # Danh sách các thư mục tĩnh
        - file:uploads/         # Thư mục uploads trong hệ thống tệp
        - classpath:/static/    # Thư mục static trong resources

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
  config:
    import: env.properties

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds