spring:
  application:
    name: AudioBook
  # MySQL database connection settings
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/audio_book?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:quyetbh}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Hibernate settings (optional)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    #Phiên bản baseline sẽ = 1 và không thực hiện bất kỳ thay đổi nào trong DB
    baseline-on-migrate: true
    baseline-version: 0


api:
  prefix: /api/v1

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: OTIGATj1p/KdUgFr2tPN2cNpqiPdM/6kh62+EzqJ8X8=
#  expiration-refresh-token: 5184000
#logging.level.org.springframework.security: DEBUG

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"